version: '3.8'

services:
  quanlynhasach-app:
    build: .
    container_name: quanlynhasach-backend
    environment:
      # Port configuration - có thể override từ .env
      - SERVER_PORT=${SERVER_PORT:-8080}
      # Database configuration
      - DB_URL=jdbc:mysql://mysql-db:3306/${DB_NAME:-quanlynhasach_db}
      - DB_USERNAME=${DB_USERNAME:-appuser}
      - DB_PASSWORD=${DB_PASSWORD}
      # JWT configuration
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION:-900000}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION:-2592000000}
      # Email configuration
      - MAIL_HOST=${MAIL_HOST:-smtp.gmail.com}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      # App configuration
      - APP_NAME=${APP_NAME:-QuanLyNhaSach}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      mysql-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT:-8080}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mysql-db:
    image: mysql:8.0
    container_name: quanlynhasach-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME:-quanlynhasach_db}
      - MYSQL_USER=${DB_USERNAME:-appuser}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    ports:
      - "${DB_HOST_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME:-appuser}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge
